#
# Basic settings.
#
# url: http://localhost:4000
# baseurl: ""
url: #
baseurl: #
title: BackEndTea
description: PHP Developer
avatar: /assets/img/me.jpg
favicon: /assets/img/me.jpg
language: en

#
# Icons
#
icons:
  rss: true
  email: BackEndTea@gmail.com
  github: BackEndTea
  bitbucket:
  twitter: BackEndTea
  facebook:
  google_plus:
  tumblr:
  behance:
  dribbble:
  flickr:
  instagram:
  linkedin: https://www.linkedin.com/in/gert-de-pagter/
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: # full URL
  steam:
  wordpress:
  youtube:

#
# Prettify url.
#
permalink: pretty

#
# Scripts.
#
google_analytics: UA-120550882-1
disqus: backendtea

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Social.
#
share_buttons:
  twitter: false
  facebook: false # needs ogp.fb.app_id
  hatena: false
ogp:
  image_url:
  fb:
    admin: # facebook admin id
    app_id: # facebook application id

#
# Gems.
#
gems:
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - .idea/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
